"""Added new tables

Revision ID: 098daa0f1a0a
Revises: 28b2567b4d52
Create Date: 2023-11-07 14:19:28.105916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098daa0f1a0a'
down_revision = '28b2567b4d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('requires_upload', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('requires_upload')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
