"""Changed relationships to patient, removed unnecessary fields

Revision ID: 1c0a0d15f4bd
Revises: 1e235db59a3a
Create Date: 2023-12-11 09:41:46.437467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0a0d15f4bd'
down_revision = '1e235db59a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_column('is_processed')

    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_upload_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('processed_image_original_image_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image_upload', ['original_upload_id'], ['id'])
        batch_op.drop_column('is_processed')
        batch_op.drop_column('original_image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('processed_image_original_image_id_fkey', 'image_upload', ['original_image_id'], ['id'])
        batch_op.drop_column('original_upload_id')

    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
