"""Separated image tables

Revision ID: 1e235db59a3a
Revises: 839bf6e3a007
Create Date: 2023-12-11 09:17:42.129760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e235db59a3a'
down_revision = '839bf6e3a007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=1000), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('original_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_image_id'], ['image_upload.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint('image_upload_original_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('original_image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('image_upload_original_image_id_fkey', 'image_upload', ['original_image_id'], ['id'])

    op.drop_table('processed_image')
    # ### end Alembic commands ###
