"""Added a parent class for images to fix the ids issue.

Revision ID: 3515a888d403
Revises: 3c31e3044574
Create Date: 2024-01-08 11:48:11.263163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3515a888d403'
down_revision = '3c31e3044574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint('image_upload_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'generic_image', ['id'], ['id'])
        batch_op.drop_column('patient_id')
        batch_op.drop_column('image')
        batch_op.drop_column('date_created')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.drop_constraint('processed_image_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'generic_image', ['id'], ['id'])
        batch_op.drop_column('patient_id')
        batch_op.drop_column('image')
        batch_op.drop_column('date_created')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('processed_image_patient_id_fkey', 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_upload_patient_id_fkey', 'patient', ['patient_id'], ['id'])

    op.drop_table('generic_image')
    # ### end Alembic commands ###
