"""Added file name to iamge

Revision ID: 3cdc11da2689
Revises: 6123a9470a89
Create Date: 2023-12-09 13:07:11.780589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdc11da2689'
down_revision = '6123a9470a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
