"""Added clinic table

Revision ID: 426f30bb5b0c
Revises: 098daa0f1a0a
Create Date: 2023-11-07 15:49:53.722827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426f30bb5b0c'
down_revision = '098daa0f1a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinic_doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinic_doctor')
    op.drop_table('clinic')
    # ### end Alembic commands ###
