"""Changed diagnostic foreign keys

Revision ID: 437517390e4f
Revises: f2b5f0bc5b70
Create Date: 2023-12-11 12:45:40.985947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437517390e4f'
down_revision = 'f2b5f0bc5b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint('image_upload_diagnostic_id_key', type_='unique')
        batch_op.drop_constraint('image_upload_diagnostic_id_fkey', type_='foreignkey')
        batch_op.drop_column('diagnostic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('image_upload_diagnostic_id_fkey', 'diagnostic', ['diagnostic_id'], ['id'])
        batch_op.create_unique_constraint('image_upload_diagnostic_id_key', ['diagnostic_id'])

    # ### end Alembic commands ###
