"""Changed appointments attributes again

Revision ID: 6123a9470a89
Revises: 4a35c424ea6b
Create Date: 2023-11-26 10:28:16.102414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6123a9470a89'
down_revision = '4a35c424ea6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
