"""Added reference to original image to the schema

Revision ID: 839bf6e3a007
Revises: 3cdc11da2689
Create Date: 2023-12-11 08:58:44.814798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839bf6e3a007'
down_revision = '3cdc11da2689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'image_upload', ['original_image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_image_id')

    # ### end Alembic commands ###
