"""Added phone number

Revision ID: 9a27e44ddf8a
Revises: 63ff3ed0f0b6
Create Date: 2023-11-08 08:49:03.952847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a27e44ddf8a'
down_revision = '63ff3ed0f0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
