"""Changed diagnostic relationship to one-to-one

Revision ID: b1b2f64a838c
Revises: 1c0a0d15f4bd
Create Date: 2023-12-11 10:05:11.229839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b2f64a838c'
down_revision = '1c0a0d15f4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.drop_constraint('diagnostic_image_id_fkey', type_='foreignkey')
        batch_op.drop_column('image_id')

    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['diagnostic_id'])
        batch_op.create_foreign_key(None, 'diagnostic', ['diagnostic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('diagnostic_id')

    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('diagnostic_image_id_fkey', 'image_upload', ['image_id'], ['id'])

    # ### end Alembic commands ###
