"""Modified the image oreign keys

Revision ID: d1bb8462a4a8
Revises: 3515a888d403
Create Date: 2024-01-08 11:52:42.535073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bb8462a4a8'
down_revision = '3515a888d403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generic_image', schema=None) as batch_op:
        batch_op.drop_constraint('generic_image_patient_id_fkey', type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('generic_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('generic_image_patient_id_fkey', 'patient', ['patient_id'], ['id'])

    # ### end Alembic commands ###
