"""Added image id to diagnostic

Revision ID: f2b5f0bc5b70
Revises: ff126ce71c4b
Create Date: 2023-12-11 12:37:50.647750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b5f0bc5b70'
down_revision = 'ff126ce71c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('diagnostic_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image_upload', ['image_id'], ['id'])
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('diagnostic_patient_id_fkey', 'patient', ['patient_id'], ['id'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
