"""Added content to diagnostic

Revision ID: ff126ce71c4b
Revises: b1b2f64a838c
Create Date: 2023-12-11 12:27:08.511188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff126ce71c4b'
down_revision = 'b1b2f64a838c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###
